name: cake_baru
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  image_picker: ^1.0.2
  webview_flutter: ^4.2.2
  http: ^1.0.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  shared_preferences: ^2.2.0
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^15.1.0+1
  appwrite: ^11.0.0
  path_provider: ^2.0.12

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  firebase_auth_mocks: ^0.13.0
  integration_test:
    sdk: flutter

fonts:
  - family: Varela
    fonts:
      - asset: assets/VarelaRound-Regular.ttf

flutter:
  assets:
    - assets/
  uses-material-design: true
